version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install-packages
      - run: sudo apt-get update
      - run: sudo apt-get install -y libgconf-2-4 xvfb gcc-multilib g++-multilib icnsutils graphicsmagick xz-utils libudev-dev libnss3 libgtk-3-0
      
workflows:
  example-workflow:
    jobs:
      - example-job
      - node/run:
            npm-run: buildwin