version: 2.1
orbs:
  node: circleci/node@5.0.3
jobs:
  install-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install-packages
      
workflows:
  example-workflow:
    jobs:
      - install-job